# Модуль Collections. 
## Counter 

In [65]:
# Импортируем объект counter из модуля Collections
from collections import Counter
# создаем пустой объект counter
c = Counter()

c['Red'] += 1
print(c)

Counter({'Red': 1})


In [66]:
# аналогичный пример со словарем - будет ошибка,
#  если изначально не задать ключ red

d = dict()

d['Red'] += 1
print(d)

KeyError: 'Red'

In [ ]:
# и рабочий вариант - когда сначала задем ключ Red

d = dict()

d['Red'] = 0
d['Red'] += 1
print(d)

{'Red': 1}


In [ ]:
# Считаем сколько проехало мимо машин
cars = ['red', 'blue', 'black', 'black', 'black', 'red', 'blue', 'red', 'white']

c = Counter()

for car in cars:
    c[car]+=1
print(c)

Counter({'red': 3, 'black': 3, 'blue': 2, 'white': 1})


In [ ]:
c = Counter(cars)
print(c)

print(c['black'])

Counter({'red': 3, 'black': 3, 'blue': 2, 'white': 1})
3


In [ ]:
# для несуществующего ключа вернет ноль, а не ошибку

print(c['purple'])


0


In [ ]:
print(sum(c.values()))

print(c.values())

9
dict_values([3, 2, 3, 1])


In [ ]:
#Пример с двумя счетчиками

cars_moscow = ['black', 'black', 'white', 'black', 'black', 'white', 'yellow', 'yellow', 'yellow']
cars_spb = ['red', 'black', 'black', 'white', 'white', 'yellow', 'yellow', 'red', 'white']

counter_moscow = Counter(cars_moscow)
counter_spb = Counter(cars_spb)

print(counter_moscow, counter_spb)
print(counter_moscow + counter_spb)

counter_moscow.subtract(counter_spb)

print(counter_moscow)

Counter({'black': 4, 'yellow': 3, 'white': 2}) Counter({'white': 3, 'red': 2, 'black': 2, 'yellow': 2})
Counter({'black': 6, 'white': 5, 'yellow': 5, 'red': 2})
Counter({'black': 2, 'yellow': 1, 'white': -1, 'red': -2})


In [ ]:

counter_moscow = Counter(cars_moscow)
counter_spb = Counter(cars_spb)

print(counter_moscow - counter_spb)

Counter({'black': 2, 'yellow': 1})


In [ ]:
print(*counter_moscow.elements())

black black black black white white yellow yellow yellow


In [ ]:
# уникальные элементы

print(list(counter_moscow))

['black', 'white', 'yellow']


In [ ]:
#преобразуем в словарь
print(dict(counter_moscow))

{'black': 4, 'white': 2, 'yellow': 3}


In [ ]:
#наиболее часто встречающиеся значения. most_common. без аргумента - просто все значения в порядке убывания
counter_moscow.most_common()
# если передать число - то выведется указанное количество наиболее часто встречающихся элементов
counter_moscow.most_common(2)

[('black', 4), ('yellow', 3)]

In [ ]:
#очищение счетчика
counter_moscow.clear()
print(counter_moscow)

Counter()


## Defaultdict

In [ ]:
students = [('Ivanov',1),('Smirnov',4),('Petrov',3),('Kuznetsova',1),
            ('Nikitina',2),('Markov',3),('Pavlov',2)]
# обычный способ сгруппировать студентов по группам

groups = dict()

for student, group in students:
    if group not in groups:
        groups[group] = list()
    groups[group].append(student)
print(groups)



{1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov']}


In [ ]:
#аналогичная задача решается с помощью defaultfict

from collections import defaultdict

#создаем defaultdict и передаем в него структуру данных
groups = defaultdict(list)

# создаем цикл в котором уже не применяем условие проврека ни отсутствие ключа в словаре
for student, group in students:
    groups[group].append(student)
print(groups)



defaultdict(<class 'list'>, {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov']})


In [ ]:
# можем обратиться как и к обычному списку по ключу
print(groups[3])

['Petrov', 'Markov']


In [ ]:
#при попытке обратиться по несуществующему ключу ошибки KeyError не возникнет, в отличае от обычного словаря
print(groups[123])

[]


## OrderedDict

In [ ]:
#Напомнин способ создания словаря через список кортежей. в кортежах, первый элемент станет ключем, а второй - значением.
data = [('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)]

client_ages = dict(data)
print(client_ages)
#порядок постоянно меняется при каждом выполнении print. Это было до версии Python 3.7. В версиях выше сортировка не меняется.

{'Ivan': 19, 'Mark': 25, 'Andrey': 23, 'Maria': 20}


In [ ]:
#OrderedDict позволяет сохранять заданный порядок
from collections import OrderedDict

data = [('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)]

client_ages = OrderedDict(data)
print(client_ages)

# Если  не планирум использовать код в версиях Python меньше 3.7, то пользоваться OrderDict не обязательно. Только для обратной совместимости

OrderedDict([('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)])


In [ ]:
from collections import OrderedDict

data = [('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)]

#Отсортируем по возрасту
client_ages = OrderedDict(sorted(data, key = lambda x: x[1] ))
print(client_ages)



OrderedDict([('Ivan', 19), ('Maria', 20), ('Andrey', 23), ('Mark', 25)])


In [ ]:
#узнать версию Python
import sys

print(sys.version)

3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]


## Deque
Double ended queue
двухконцевая очередь 

очередь - кто первый пришел, тот первый и выйдет FIFO
стек - первой выходит те, кто приходят последним LIFO

Объект Deque объединяет в себе свойства как стека, так и очереди

Очередь — это упорядоченный тип данных, который обладает двумя ключевыми функциями: добавление элемента в конец очереди и извлечение самого первого элемента из очереди. То есть очередь подразумевает, что тот элемент, который первым добавлен в очередь, будет первым потом и обработан. Всё как в обычной очереди! Этот принцип сокращённо также называется FIFO (от англ. First In — First Out, «первым пришёл — первым ушёл»).

Стек (от англ. stack — стопка) — это упорядоченный тип данных, который обладает двумя основными функциями: добавление элемента в конец стека и извлечение элемента из конца стека. Эта структура данных также называется рюкзаком. Действительно, представьте себе, что вы набили вещами рюкзак. Теперь, когда вы решите достать из него самую верхнюю вещь, что это будет за вещь? Верно — та самая, которую вы убрали в рюкзак последней. Поэтому принцип стека (рюкзака) также сокращённо называется LIFO (Last In — First Out, «последним пришёл — первым ушёл»)

Наконец, существует структура данных deque (читается как «дек», англ. double-ended queue — двухконцевая очередь). Она объединяет в себе возможности и стека, и очереди: содержит функции, которые позволяют добавлять элементы в начало или в конец очереди, а также извлекать первый или последний элемент из неё. 

In [ ]:
from collections import deque

dq = deque()
print(dq)

deque([])


У deque есть четыре ключевые функции:

append (добавить элемент в конец дека);
appendleft (добавить элемент в начало дека);
pop (удалить и вернуть элемент из конца дека);
popleft (удалить и вернуть элемент из начала дека).

Также в очередь возможно добавить сразу несколько элементов из итерируемого объекта в дек. Для этого используют функции extend (добавить в конец дека) и extendleft (добавить в начало дека).

In [ ]:
# создадим очередь клиентов в техподдержку

clients = deque()

clients.append('Ivanov')
clients.append('Petrov')
clients.append('Smirnov')
clients.append("Tikhonova")

print(clients)

deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])


In [ ]:
print(clients[2])

Smirnov


In [ ]:
# чтобы выбрать очередное значение из очереди. При этом каждый элемент, который мы получаем, автоматически удаляется из очереди

first_client = clients.popleft()
second_client = clients.popleft()

print(first_client)
print(second_client)

print(clients)

Ivanov
Petrov
deque(['Smirnov', 'Tikhonova'])


In [ ]:
#Добвляем элемент слева

clients.appendleft('VIP-client')

print(clients)

deque(['VIP-client', 'Smirnov', 'Tikhonova'])


In [ ]:
#удаляем элемент справа

tired_client = clients.pop()

print(clients)

deque(['VIP-client', 'Smirnov'])


In [ ]:
#в очередм можно добавить также объекты из какого-либо итерируемого объекта.
shop = deque([1, 2, 3, 4, 5])

print(shop)

shop.extend([11, 12, 13, 14, 15, 16, 17])

print(shop)

deque([1, 2, 3, 4, 5])
deque([1, 2, 3, 4, 5, 11, 12, 13, 14, 15, 16, 17])


Обратите внимание, что «клиенты из автобуса» оказались в очереди не в том порядке, в каком они «выходили из автобуса». То есть добавленные номера не только приписаны перед записанными в очереди номерами, но также порядок добавленных элементов поменялся на обратный. Это связано с тем, что действие функции extendleft аналогично многократному применению функции appendleft, поэтому самый последний клиент из автобуса оказался в итоге первым в очереди.

In [ ]:
#аналогично можно добавить элементы слева
shop = deque([1, 2, 3, 4, 5])

print(shop)

shop.extendleft([11, 12, 13, 14, 15, 16, 17])

print(shop)


deque([1, 2, 3, 4, 5])
deque([17, 16, 15, 14, 13, 12, 11, 1, 2, 3, 4, 5])


In [ ]:
#очередь с ограниченной длинной

limited = deque(maxlen = 3)

print(limited)

deque([], maxlen=3)


In [ ]:
limited.extend([1, 2, 3])
print(limited)

print(limited.append(8))

print(limited)


deque([1, 2, 3], maxlen=3)
None
deque([2, 3, 8], maxlen=3)


In [ ]:
#очереди с ограниченной длинной можно использовать для вычисления скользящих средних

temps = [20.6, 19.4, 19.0, 19.0, 22.1,
        22.5, 22.8, 24.1, 25.6, 27.0,
        27.0, 25.6, 26.8, 27.3, 22.5,
        25.4, 24.4, 23.7, 23.6, 22.6,
        20.4, 17.9, 17.3, 17.3, 18.1,
        20.1, 22.2, 19.8, 21.3, 21.3,
        21.9]

days = deque(maxlen=7)
 
for temp in temps:
    # Добавляем температуру в очередь
    days.append(temp)
    # Если длина очереди оказалась равной максимальной длине очереди (7),
    # печатаем среднюю температуру за последние 7 дней
    if len(days) == days.maxlen:
        print(round(sum(days) / len(days), 2), end='; ')
# Напечатаем пустую строку, чтобы завершить действие параметра
# end. Иначе следующая строка окажется напечатанной на предыдущей
print("")
# Результат:
# 20.77; 21.27; 22.16; 23.3; 24.44; 24.94; 25.56; 26.2; 25.97;
# 25.94; 25.57; 25.1; 24.81; 24.21; 23.23; 22.57; 21.41; 20.4;
# 19.6; 19.1; 19.04; 18.96; 19.44; 20.01; 20.67;

In [ ]:
#очередь можно развернуть

dq = deque([1, 2, 3])

dq.reverse()

print(dq)

deque([3, 2, 1])


In [ ]:
# перенести элементы из конца в начало

dq = deque([1, 2, 3, 4, 5])
print(dq)

# используем rotate и передаем количество элементов, которые нужно перенести
dq.rotate(2)

print(dq)

# если передать отрицательное число, то элементы будут перенесены из начала в конец

dq.rotate(-2)

print(dq)


deque([1, 2, 3, 4, 5])
deque([4, 5, 1, 2, 3])
deque([1, 2, 3, 4, 5])


In [ ]:
#как и у списков у очередей есть функции

dq = deque([1, 2, 3, 4, 5, 6, 7, 3, 4, 4, 5, 6, 7])

#определяем индекс первого вхождения элемента
print(dq.index(4))

#считаем количество элементов
print(dq.count(4))

3
3


In [ ]:
#если в индексе передать отстствующий элемент - то возникнет ошибка

#print(dq.index(25))

#а посчитать отсутствующий элемент можно

print(dq.count(25))

0


In [ ]:
#очередь можно очистить

dq.clear()

print(dq)

deque([])


## Задания

In [ ]:
from collections import deque

#Функция проверки правильности последовательность из круглых скобок
def brackets(line):
    # Если строка пустая - возвращаем True
    if len(line) == 0:
        return True
    
    #Создаем стек для хранения открывающих скобок
    open_brackets = deque()
    
    #Создаем цикл для прохода по элементам строки
    for element in line:
        #открывающую скобку помещаем в стек
        if element == '(':
            open_brackets.append(element)
        #для закрывающей скобки удаляем соответствующую ей открывающую
        if element == ')':
            #предварительно проверяем на наличие в стеке хотя бы одной открывающей скобки. если таких нет - возвращаем False
            if len(open_brackets) == 0:
                return False
            #удаляем открывающую
            open_brackets.pop()
    
    #После того как прошли по всей строке - проверяем наличие в стеке оставшихся скобок.
    if len(open_brackets) == 0:
        #если все скобки закрыты - возвращаем True
        return True
    else:
        #Иначе - возвращаем False
          return False


print(brackets("(()())"))
# True
print(brackets(""))
# True
print(brackets("(()()))"))
# False
            
    



True
True
False


In [ ]:
from hidden import north, center, south
from collections import Counter
# Пишите здесь команды, которые помогут
# найти ответы на вопросы

#это значения переменных north, center, south из hidden
#[['Milk', 'Milk', 'Beer'], ['Chocolate', 'Bread', 'Chips'], ['Cola', 'Cola', 'Yoghurt', 'Soap', 'Beer', 'Chips', 'Milk'], ['Soap', 'Soap', 'Cola', 'Cola', 'Chips'], ['Milk', 'Beer', 'Meat', 'Ketchup', 'Cola', 'Cola', 'Chips', 'Chips', 'Cola', 'Cola'], ['Beer', 'Bread', 'Bread', 'Beer', 'Beer', 'Beer', 'Bread', 'Cheese'], ['Yoghurt', 'Beer', 'Chips', 'Milk', 'Soap', 'Cola', 'Cola', 'Cola', 'Beer', 'Cola', 'Cola', 'Cola', 'Beer', 'Ketchup', 'Beer', 'Beer', 'Beer', 'Soap'], ['Milk', 'Cola', 'Cola', 'Beer', 'Beer', 'Bread', 'Bread', 'Soap', 'Cola', 'Cola', 'Beer', 'Meat', 'Bread', 'Chips'], ['Beer', 'Beer', 'Beer', 'Chips', 'Milk', 'Cola', 'Chocolate', 'Beer', 'Chocolate', 'Beer', 'Beer', 'Cola', 'Meat', 'Yoghurt', 'Beer'], ['Bread'], ['Chocolate', 'Beer', 'Meat', 'Yoghurt'], ['Cola', 'Beer', 'Beer', 'Beer', 'Chocolate', 'Beer', 'Soap', 'Beer', 'Chips', 'Soap', 'Chocolate', 'Bread', 'Chips', 'Cola', 'Bread', 'Beer', 'Cola', 'Bread'], ['Chips', 'Cola', 'Beer', 'Chips', 'Cola', 'Cola', 'Beer', 'Soap', 'Yoghurt', 'Yoghurt', 'Cola', 'Bread', 'Beer', 'Chocolate', 'Chips', 'Bread', 'Beer', 'Bread'], ['Cola', 'Chocolate'], ['Chocolate', 'Cola', 'Meat', 'Cola', 'Ketchup', 'Cola', 'Chocolate', 'Bread', 'Chocolate', 'Chocolate', 'Meat'], ['Bread', 'Milk', 'Chips', 'Ketchup', 'Cola', 'Cola', 'Cola', 'Beer', 'Beer', 'Soap', 'Beer', 'Cola'], ['Yoghurt', 'Milk', 'Soap', 'Bread', 'Cola', 'Cola', 'Milk', 'Bread', 'Chips', 'Cheese', 'Milk', 'Yoghurt', 'Bread', 'Yoghurt'], ['Cola', 'Ketchup'], ['Cola', 'Yoghurt', 'Bread', 'Cola', 'Cola', 'Chips', 'Yoghurt', 'Milk', 'Beer', 'Chips', 'Bread', 'Beer', 'Beer', 'Cola', 'Bread', 'Beer', 'Beer', 'Cheese'], ['Beer', 'Cheese', 'Ketchup', 'Beer'], ['Beer', 'Beer', 'Beer'], ['Soap', 'Beer', 'Beer', 'Chocolate', 'Cola', 'Chocolate', 'Bread', 'Beer', 'Milk', 'Bread', 'Beer', 'Chocolate', 'Bread', 'Cola', 'Cola', 'Cheese', 'Beer', 'Cola', 'Soap', 'Yoghurt'], ['Beer', 'Chocolate'], ['Cola', 'Beer'], ['Yoghurt', 'Beer', 'Yoghurt', 'Yoghurt', 'Chips', 'Meat', 'Beer', 'Chocolate', 'Cola', 'Cola', 'Chips', 'Bread'], ['Cola', 'Cola', 'Cola', 'Cola', 'Cola', 'Bread', 'Chips', 'Soap', 'Cola', 'Chocolate', 'Beer', 'Beer'], ['Beer', 'Cola', 'Cola', 'Bread', 'Soap', 'Beer', 'Meat', 'Beer', 'Beer', 'Beer', 'Cola', 'Chips', 'Beer', 'Cola', 'Cola', 'Bread', 'Cheese', 'Beer'], ['Cola', 'Cola', 'Ketchup', 'Beer', 'Yoghurt', 'Bread'], ['Chips', 'Yoghurt', 'Cola', 'Cola', 'Cola', 'Chocolate', 'Chips', 'Bread', 'Chocolate', 'Yoghurt', 'Chocolate', 'Milk', 'Bread', 'Bread', 'Soap', 'Milk', 'Soap', 'Cola', 'Bread', 'Beer'], ['Beer', 'Beer', 'Ketchup', 'Cola', 'Beer', 'Bread', 'Beer', 'Cola', 'Beer', 'Chocolate'], ['Beer', 'Chocolate', 'Cola', 'Beer', 'Yoghurt', 'Milk', 'Bread', 'Cheese', 'Yoghurt', 'Beer', 'Cola', 'Yoghurt', 'Cola', 'Soap', 'Beer', 'Bread', 'Meat', 'Bread', 'Cola'], ['Beer', 'Cola', 'Chips', 'Cola'], ['Cola', 'Cola', 'Beer', 'Cheese'], ['Bread', 'Soap', 'Ketchup', 'Chocolate', 'Beer', 'Cola', 'Chocolate', 'Cola', 'Cola', 'Yoghurt', 'Beer', 'Bread', 'Cola', 'Ketchup', 'Beer'], ['Bread'], ['Bread', 'Beer', 'Yoghurt', 'Yoghurt', 'Bread', 'Milk', 'Soap', 'Meat', 'Bread', 'Beer', 'Cola', 'Milk', 'Milk', 'Bread', 'Beer', 'Cola', 'Ketchup', 'Cola'], ['Bread', 'Beer', 'Bread', 'Yoghurt', 'Beer', 'Bread', 'Cola', 'Cola', 'Cola', 'Beer', 'Bread', 'Milk', 'Chips', 'Cola', 'Beer', 'Bread', 'Soap', 'Bread', 'Yoghurt', 'Bread'], ['Yoghurt', 'Beer', 'Cola', 'Beer', 'Beer', 'Beer'], ['Chips', 'Chocolate', 'Soap', 'Chocolate', 'Cola', 'Bread', 'Beer', 'Cola', 'Beer', 'Ketchup', 'Chocolate', 'Ketchup', 'Ketchup', 'Cheese', 'Chips', 'Beer', 'Chips', 'Chocolate'], ['Bread', 'Cola', 'Cola', 'Beer', 'Bread', 'Bread', 'Beer', 'Chocolate', 'Bread', 'Cola', 'Milk', 'Chips', 'Meat', 'Beer', 'Beer', 'Soap', 'Bread'], ['Beer', 'Beer', 'Bread', 'Chips', 'Beer', 'Bread', 'Bread', 'Chips', 'Beer'], ['Yoghurt', 'Bread', 'Cola', 'Bread', 'Cola', 'Bread', 'Meat', 'Cola', 'Bread', 'Beer', 'Soap', 'Chips'], ['Bread', 'Beer'], ['Milk', 'Beer', 'Meat', 'Cola', 'Beer', 'Cola', 'Cola'], ['Beer', 'Chips', 'Yoghurt', 'Beer', 'Cola', 'Beer', 'Cola', 'Cola', 'Soap', 'Cola'], ['Bread', 'Cola', 'Cola', 'Meat'], ['Cola', 'Chocolate', 'Meat', 'Beer', 'Cola', 'Bread', 'Chips', 'Beer', 'Chips', 'Chips', 'Cola'], ['Bread', 'Cola', 'Cola', 'Cola', 'Beer', 'Cola', 'Yoghurt', 'Beer', 'Chips', 'Cola', 'Chocolate', 'Chips', 'Cola', 'Cola', 'Cola', 'Cola', 'Bread', 'Cola'], ['Cola', 'Soap', 'Cola'], ['Soap', 'Chips', 'Cola', 'Beer', 'Bread', 'Soap', 'Cheese', 'Bread', 'Beer', 'Chocolate']]
#[['Meat', 'Beer', 'Soap', 'Beer', 'Cheese', 'Cola', 'Milk', 'Soap', 'Cola', 'Meat', 'Bread', 'Chocolate', 'Chips'], ['Soap', 'Beer', 'Chips', 'Bread', 'Beer', 'Beer', 'Beer', 'Cheese', 'Cheese', 'Beer', 'Chips', 'Chocolate', 'Chips', 'Cheese', 'Bread', 'Cola', 'Cola', 'Beer'], ['Cola', 'Soap', 'Bread', 'Milk', 'Beer', 'Meat', 'Bread', 'Bread'], ['Ketchup', 'Beer', 'Ketchup', 'Chocolate', 'Milk', 'Milk', 'Bread', 'Beer'], ['Beer', 'Beer', 'Meat', 'Ketchup', 'Soap', 'Bread', 'Cola', 'Beer'], ['Meat', 'Bread', 'Milk', 'Cheese', 'Soap', 'Beer', 'Milk', 'Cheese', 'Cola', 'Beer', 'Chips', 'Bread', 'Ketchup', 'Chocolate', 'Bread', 'Milk'], ['Yoghurt'], ['Beer', 'Milk', 'Chips', 'Soap', 'Chips', 'Milk', 'Beer', 'Chips', 'Bread', 'Meat', 'Milk'], ['Yoghurt', 'Beer', 'Cola', 'Cola', 'Beer', 'Soap', 'Cheese', 'Soap', 'Bread', 'Cola', 'Yoghurt', 'Ketchup', 'Beer', 'Milk'], ['Milk', 'Cola', 'Bread', 'Cola', 'Bread', 'Beer', 'Beer', 'Beer'], ['Yoghurt', 'Cola'], ['Bread', 'Yoghurt', 'Chips', 'Ketchup', 'Meat', 'Bread', 'Beer', 'Yoghurt', 'Cola', 'Cola'], ['Chips', 'Chocolate', 'Chips', 'Meat', 'Bread', 'Cheese', 'Bread', 'Yoghurt'], ['Ketchup', 'Soap', 'Chocolate', 'Bread'], ['Chips', 'Beer', 'Chips', 'Cola', 'Cheese', 'Soap', 'Ketchup', 'Meat', 'Cola', 'Chips', 'Beer', 'Chocolate', 'Beer', 'Milk', 'Bread', 'Ketchup', 'Chips', 'Cheese', 'Ketchup'], ['Beer', 'Milk', 'Soap', 'Chips', 'Soap', 'Bread', 'Bread', 'Milk', 'Beer'], ['Cola', 'Chips', 'Meat', 'Cola', 'Beer', 'Chocolate', 'Bread', 'Bread', 'Chips', 'Soap', 'Chocolate', 'Chips', 'Beer'], ['Meat', 'Cola', 'Chips', 'Bread', 'Chips', 'Chocolate', 'Bread', 'Meat', 'Bread', 'Yoghurt', 'Cheese', 'Bread', 'Chips', 'Cola'], ['Chips', 'Cheese', 'Bread', 'Beer', 'Bread', 'Chips', 'Chocolate', 'Bread', 'Cola', 'Cola', 'Chocolate', 'Chocolate', 'Bread', 'Meat', 'Chips'], ['Bread', 'Milk', 'Bread', 'Cheese', 'Bread', 'Cheese', 'Ketchup', 'Beer', 'Cheese', 'Cola', 'Milk', 'Milk', 'Bread', 'Beer', 'Bread', 'Chips'], ['Yoghurt'], ['Bread', 'Bread', 'Chips', 'Cheese', 'Bread', 'Beer', 'Cola', 'Ketchup', 'Bread', 'Chips', 'Chocolate', 'Meat', 'Milk', 'Beer', 'Milk', 'Cheese', 'Bread', 'Meat', 'Bread', 'Cola'], ['Bread', 'Meat', 'Meat', 'Milk', 'Chips', 'Soap', 'Yoghurt', 'Chips', 'Beer', 'Yoghurt'], ['Bread', 'Soap', 'Bread', 'Cola', 'Bread'], ['Cola', 'Bread', 'Meat', 'Cola', 'Meat', 'Chocolate', 'Chips', 'Meat', 'Chips'], ['Chips', 'Cheese', 'Cheese', 'Meat'], ['Chips', 'Meat', 'Soap', 'Cheese', 'Bread', 'Cola', 'Bread', 'Beer', 'Meat', 'Cola', 'Bread', 'Cola', 'Ketchup', 'Bread'], ['Chips', 'Cheese', 'Milk', 'Meat', 'Milk', 'Beer', 'Chocolate', 'Ketchup', 'Cola', 'Cheese', 'Beer'], ['Beer', 'Ketchup', 'Yoghurt', 'Ketchup', 'Chocolate', 'Bread', 'Beer', 'Ketchup', 'Chocolate', 'Cola', 'Chocolate', 'Ketchup', 'Cola', 'Meat', 'Chips', 'Soap', 'Meat'], ['Meat', 'Milk'], ['Cola', 'Beer', 'Yoghurt', 'Beer', 'Bread', 'Cola'], ['Chips', 'Meat', 'Cheese', 'Ketchup', 'Chips', 'Bread', 'Bread', 'Chips', 'Chips', 'Bread', 'Milk', 'Ketchup', 'Cola', 'Cola', 'Beer'], ['Beer', 'Bread', 'Cheese', 'Bread', 'Cola', 'Cheese', 'Cheese', 'Beer', 'Milk', 'Bread', 'Chocolate', 'Cheese', 'Beer', 'Bread', 'Beer', 'Cola', 'Yoghurt', 'Beer', 'Beer', 'Chips'], ['Bread', 'Chips', 'Bread', 'Cola', 'Chips', 'Chocolate', 'Cheese', 'Beer', 'Chips', 'Milk', 'Milk', 'Beer', 'Cola', 'Meat', 'Cola', 'Bread', 'Cola', 'Chocolate', 'Chocolate', 'Cola'], ['Soap', 'Yoghurt', 'Chips', 'Beer', 'Chips', 'Milk', 'Cheese', 'Meat', 'Beer', 'Bread', 'Ketchup', 'Bread', 'Bread', 'Cheese', 'Milk', 'Beer', 'Beer', 'Soap', 'Bread'], ['Cola', 'Bread', 'Cheese', 'Ketchup', 'Beer', 'Chips', 'Meat', 'Chocolate', 'Chips', 'Cola', 'Beer', 'Beer', 'Cola'], ['Ketchup', 'Beer', 'Chocolate', 'Bread', 'Yoghurt', 'Beer', 'Cheese'], ['Bread', 'Chocolate', 'Bread', 'Milk'], ['Meat', 'Yoghurt', 'Bread', 'Yoghurt', 'Cola', 'Ketchup'], ['Ketchup', 'Bread', 'Bread', 'Chocolate', 'Chocolate', 'Chocolate', 'Bread', 'Bread', 'Beer', 'Chocolate', 'Bread', 'Milk'], ['Bread', 'Cheese', 'Soap', 'Soap', 'Chips', 'Chips'], ['Ketchup', 'Chocolate', 'Chips', 'Milk', 'Soap', 'Soap', 'Ketchup', 'Bread', 'Ketchup', 'Cola', 'Cheese', 'Beer', 'Ketchup', 'Bread'], ['Bread', 'Milk', 'Beer', 'Yoghurt', 'Meat', 'Ketchup', 'Meat', 'Meat', 'Bread', 'Milk', 'Cheese', 'Beer', 'Yoghurt', 'Milk', 'Bread', 'Cola'], ['Chips', 'Cola', 'Milk', 'Chocolate', 'Beer', 'Beer', 'Chips', 'Bread', 'Beer', 'Beer', 'Bread', 'Beer', 'Ketchup', 'Milk', 'Yoghurt', 'Ketchup', 'Cola', 'Ketchup', 'Chips', 'Meat'], ['Beer', 'Bread', 'Soap', 'Cheese', 'Meat', 'Soap'], ['Beer', 'Meat', 'Beer', 'Yoghurt', 'Soap', 'Chips', 'Meat', 'Cheese', 'Milk', 'Bread', 'Meat', 'Beer', 'Milk'], ['Chips', 'Meat', 'Bread'], ['Chocolate', 'Soap', 'Bread', 'Chips', 'Chips', 'Yoghurt', 'Chips', 'Cola', 'Cola', 'Cola', 'Beer', 'Milk', 'Milk', 'Bread', 'Bread', 'Meat'], ['Meat', 'Chocolate', 'Chips', 'Chips', 'Yoghurt', 'Yoghurt', 'Beer', 'Cola', 'Cheese', 'Milk', 'Beer'], ['Meat', 'Chocolate', 'Yoghurt', 'Cola', 'Cheese', 'Meat', 'Bread', 'Beer', 'Meat', 'Beer', 'Yoghurt', 'Cola', 'Bread']]
#[['Cola', 'Meat', 'Cheese', 'Yoghurt', 'Beer', 'Milk', 'Milk', 'Meat', 'Cola', 'Cola', 'Cheese', 'Beer', 'Yoghurt', 'Beer', 'Bread', 'Bread', 'Milk', 'Cheese', 'Chocolate'], ['Soap', 'Milk', 'Cola'], ['Milk', 'Bread', 'Yoghurt', 'Meat', 'Meat'], ['Bread', 'Milk', 'Beer'], ['Beer'], ['Chocolate', 'Meat', 'Chocolate', 'Cola', 'Cola', 'Cola', 'Cola', 'Yoghurt', 'Bread', 'Meat', 'Soap', 'Soap', 'Milk', 'Milk', 'Cola'], ['Beer', 'Beer', 'Meat', 'Chips', 'Bread', 'Bread', 'Bread', 'Bread', 'Milk', 'Cola', 'Chocolate', 'Bread', 'Beer', 'Chips', 'Bread', 'Bread', 'Yoghurt'], ['Chips', 'Milk', 'Soap'], ['Meat', 'Beer', 'Milk', 'Chocolate', 'Bread', 'Yoghurt'], ['Chips', 'Meat', 'Chocolate', 'Bread', 'Cola', 'Cola', 'Chocolate', 'Meat', 'Yoghurt', 'Milk'], ['Bread', 'Soap', 'Bread', 'Meat', 'Beer', 'Yoghurt', 'Milk', 'Cola', 'Bread', 'Ketchup'], ['Meat', 'Milk'], ['Meat', 'Beer', 'Yoghurt'], ['Cola', 'Bread', 'Cola', 'Chocolate', 'Chips', 'Meat', 'Cheese'], ['Milk', 'Milk', 'Cheese', 'Meat'], ['Chips', 'Yoghurt', 'Cheese', 'Soap', 'Ketchup', 'Cheese', 'Soap', 'Beer', 'Ketchup', 'Ketchup', 'Milk', 'Bread', 'Bread', 'Beer'], ['Meat'], ['Ketchup', 'Bread', 'Beer', 'Milk', 'Bread', 'Meat', 'Ketchup', 'Cheese'], ['Meat', 'Chips', 'Bread', 'Meat', 'Milk', 'Soap', 'Chocolate', 'Meat', 'Chocolate', 'Chocolate', 'Bread', 'Cheese', 'Soap', 'Cola', 'Yoghurt'], ['Cheese', 'Milk', 'Bread', 'Milk', 'Chips', 'Chips', 'Meat', 'Beer', 'Chocolate', 'Chocolate'], ['Ketchup', 'Beer', 'Cheese', 'Cola'], ['Chocolate', 'Cheese', 'Bread'], ['Milk', 'Yoghurt', 'Ketchup', 'Beer', 'Meat', 'Chips', 'Yoghurt', 'Meat', 'Bread', 'Chips'], ['Yoghurt', 'Milk', 'Ketchup', 'Yoghurt', 'Beer', 'Cheese', 'Bread', 'Bread', 'Ketchup', 'Bread', 'Bread', 'Yoghurt', 'Meat'], ['Soap', 'Meat', 'Bread', 'Beer', 'Milk'], ['Beer', 'Cola', 'Beer', 'Meat', 'Meat', 'Cheese', 'Meat', 'Chocolate', 'Bread', 'Ketchup', 'Milk', 'Soap'], ['Cheese', 'Chocolate', 'Milk', 'Chocolate', 'Cola', 'Bread', 'Chips', 'Cheese', 'Soap', 'Ketchup', 'Cheese', 'Chips', 'Cheese', 'Cola', 'Chocolate', 'Beer'], ['Bread', 'Bread', 'Cola', 'Ketchup', 'Cola', 'Bread', 'Meat', 'Yoghurt', 'Milk', 'Beer', 'Beer', 'Cheese', 'Meat', 'Bread', 'Cheese', 'Meat', 'Chocolate'], ['Chocolate', 'Soap', 'Chips', 'Beer', 'Bread', 'Yoghurt', 'Chips', 'Chocolate', 'Beer', 'Cheese', 'Cola', 'Milk', 'Chips', 'Milk', 'Ketchup', 'Cola', 'Meat', 'Beer', 'Cheese', 'Yoghurt'], ['Soap'], ['Meat', 'Beer', 'Milk', 'Bread', 'Beer', 'Cheese', 'Chocolate', 'Beer', 'Beer', 'Milk', 'Beer', 'Bread', 'Meat', 'Beer', 'Chocolate', 'Beer', 'Soap', 'Chips', 'Cola'], ['Cola', 'Beer', 'Meat', 'Chips', 'Soap', 'Cola', 'Bread', 'Cola', 'Bread', 'Chips', 'Ketchup', 'Ketchup', 'Beer', 'Ketchup', 'Cola', 'Milk', 'Cheese'], ['Cheese', 'Milk', 'Chips', 'Bread', 'Yoghurt', 'Soap', 'Beer', 'Chips', 'Ketchup', 'Chips', 'Beer', 'Yoghurt', 'Cola', 'Cheese', 'Chocolate', 'Beer'], ['Meat', 'Bread', 'Meat', 'Bread'], ['Cola', 'Beer', 'Yoghurt'], ['Beer', 'Bread', 'Beer', 'Meat', 'Bread', 'Milk', 'Soap', 'Milk', 'Chocolate', 'Meat', 'Meat', 'Meat', 'Chips', 'Chocolate', 'Meat'], ['Beer', 'Cola', 'Chocolate', 'Bread', 'Cheese', 'Cheese'], ['Milk', 'Chips', 'Cola', 'Milk', 'Bread', 'Bread', 'Beer', 'Milk', 'Cola', 'Chocolate', 'Chocolate', 'Meat', 'Cola', 'Cola', 'Beer', 'Cola', 'Chocolate', 'Bread', 'Bread', 'Cola'], ['Chocolate', 'Chocolate', 'Beer', 'Beer', 'Bread', 'Yoghurt', 'Meat', 'Cola', 'Yoghurt'], ['Ketchup', 'Cola', 'Ketchup', 'Yoghurt', 'Chips', 'Soap', 'Soap', 'Chocolate', 'Chocolate', 'Bread', 'Beer', 'Meat'], ['Bread', 'Meat', 'Soap', 'Cola', 'Bread', 'Cola', 'Yoghurt', 'Meat', 'Bread', 'Cola', 'Cola', 'Ketchup', 'Beer', 'Bread', 'Milk', 'Yoghurt', 'Meat'], ['Chocolate', 'Yoghurt', 'Bread'], ['Meat', 'Bread', 'Bread', 'Bread'], ['Beer', 'Milk', 'Cola', 'Ketchup', 'Cola', 'Cheese', 'Meat', 'Chocolate'], ['Soap', 'Beer', 'Chocolate', 'Chocolate', 'Cola', 'Cola', 'Yoghurt', 'Ketchup', 'Milk'], ['Meat', 'Yoghurt', 'Bread', 'Ketchup', 'Ketchup', 'Milk', 'Meat'], ['Ketchup', 'Soap', 'Chips', 'Ketchup', 'Bread', 'Chocolate', 'Milk', 'Bread', 'Bread', 'Ketchup', 'Cola', 'Meat', 'Milk', 'Bread', 'Cola'], ['Meat', 'Beer', 'Yoghurt', 'Chips', 'Beer', 'Meat', 'Cola', 'Beer', 'Meat', 'Ketchup', 'Milk', 'Cola', 'Yoghurt', 'Beer', 'Meat', 'Bread', 'Bread'], ['Meat', 'Soap', 'Cheese', 'Ketchup', 'Cola', 'Cola', 'Bread', 'Chips', 'Meat', 'Cola', 'Bread', 'Beer', 'Beer', 'Beer'], ['Meat', 'Yoghurt', 'Bread', 'Milk', 'Beer', 'Beer']]


print(north )
#создаем функцию распаковки списков
def flatten(list_nested):
    list_flatten = list()
    for element in list_nested:
        list_flatten.extend(element)
    return list_flatten

#распаковываем списки
north  = flatten(north)
center = flatten(center)
south  = flatten(south)

#в каком магазине куплено больше всего товаров

#print(max([len(north), len(center), len(south)]))

def max_order_shop(**qwargs):
    print(qwargs)
    for key in qwargs:
       #print(key)
       if qwargs[key] == max(qwargs.values()):
           print('max orders was in shop: {}'.format(key))
       # pass
    return 1

max_order_shop(north = len(north), center = len(center), south = len(south))

#создаем счетчики
north_counter = Counter(north)
center_counter = Counter(center)
south_counter = Counter(south)
#north = list(north)


#самый редкий товар в north
print(north_counter.most_common()[-1])

#Выберите товар, который в магазине center покупали чаще, чем в магазине north:
print(center_counter - north_counter )
#center_counter.subtract(north_counter)
#print(center_counter)

#Есть ли такой товар, который в одном из магазинов покупали чаще, чем в двух других вместе взятых? Если да, выберите магазин с настолько популярным товаром:

def more_offen_in_other_two_combined(counter_1, counter_2, counter_3):
    for element in counter_1:
        if counter_1[element] > (counter_2 + counter_3)[element]:
            print( element, counter_1[element])
    return 1
    
more_offen_in_other_two_combined(north_counter, center_counter, south_counter)

more_offen_in_other_two_combined( center_counter, south_counter, north_counter)
more_offen_in_other_two_combined( south_counter, north_counter, center_counter)

#Определите суммарное число продаж каждого товара во всех магазинах, сложив все объекты-счётчики. Сколько раз был куплен второй по популярности товар? Запишите ответ в числовой форме.

print((north_counter + center_counter + south_counter).most_common(2))

In [ ]:
from collections import OrderedDict

ratings = [('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8),
           ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1),
           ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)]
         
# Отсортируйте список ratings по убыванию рейтинга. Для кафе
# с одинаковым рейтингом отсортируйте кортежи по названию.

ratings.sort(key = lambda x: ((-1)*x[1], x[0]))
#print(ratings)

# Сохраните данные с рейтингом в словарь cafes, где ключами являются
# названия кафе, а значениями - их рейтинг.
cafes = OrderedDict()

for cafe in ratings:
    cafes[cafe[0]] = cafe[1]

print(cafes)

# Модуль NumPy. 
## Типы данных

библиотека numPy позволяет работать с большими объемами чисел

In [69]:
import numpy as np

a = np.int8(25)
print(a)

print(type(a))

25
<class 'numpy.int8'>


In [71]:
#получить информацию о целочисленном типе данных
np.iinfo(np.int8)



iinfo(min=-128, max=127, dtype=int8)

In [72]:
#можно применить к конкретной переменной
np.iinfo(a)

iinfo(min=-128, max=127, dtype=int8)

In [76]:
#типы без знаков (только положительные)
b = np.uint64(124)

print(b)

print(type(b))

np.iinfo(b)

124
<class 'numpy.uint64'>


iinfo(min=0, max=18446744073709551615, dtype=uint64)

In [77]:
a = np.uint32(123)

a = 2
#если положить просто число в эту же переменную - то тип станет просто int
print(type(a))


<class 'int'>


In [78]:
a = np.uint32(123)

a = a + 50
#если прибавляем другое число - то тип сохраняется
print(type(a))

<class 'numpy.int64'>


In [84]:
a = np.int32(1000)

b = a + 50
#
print(type(b))

<class 'numpy.int32'>


In [85]:
a = np.int32(1000)

b = np.int8(50)

c = a + b
#приводится к старшему формату
print(type(c))

<class 'numpy.int32'>


In [86]:
np.iinfo(np.int32)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [87]:
a = np.int32(2147483610)
b = np.int32(2147483605)
#переполнение и ошибка
print( a + b )

-81


C:\Users\Ulyana\AppData\Local\Temp\ipykernel_7708\1622642964.py:4: RuntimeWarning: overflow encountered in long_scalars
  print( a + b )


In [88]:
a = np.int8(260)
#часть числа теряется, но ошибки нет
print(a)

4


In [90]:
#числа с плавающей точкой

np.finfo(np.float16)




finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)

In [91]:
np.finfo(np.float32)

finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)

In [96]:
print(np.float16(4.12))

print(np.float16(4.123))

print(np.float16(4.124))

print(np.float16(4.125))

4.12
4.12
4.125
4.125


In [98]:
#все типы данных в numpy
print(np.sctypeDict)
print(len(np.sctypeDict))

{'?': <class 'numpy.bool_'>, 0: <class 'numpy.bool_'>, 'byte': <class 'numpy.int8'>, 'b': <class 'numpy.int8'>, 1: <class 'numpy.int8'>, 'ubyte': <class 'numpy.uint8'>, 'B': <class 'numpy.uint8'>, 2: <class 'numpy.uint8'>, 'short': <class 'numpy.int16'>, 'h': <class 'numpy.int16'>, 3: <class 'numpy.int16'>, 'ushort': <class 'numpy.uint16'>, 'H': <class 'numpy.uint16'>, 4: <class 'numpy.uint16'>, 'i': <class 'numpy.intc'>, 5: <class 'numpy.intc'>, 'uint': <class 'numpy.uint32'>, 'I': <class 'numpy.uintc'>, 6: <class 'numpy.uintc'>, 'intp': <class 'numpy.int64'>, 'p': <class 'numpy.int64'>, 9: <class 'numpy.int64'>, 'uintp': <class 'numpy.uint64'>, 'P': <class 'numpy.uint64'>, 10: <class 'numpy.uint64'>, 'long': <class 'numpy.int32'>, 'l': <class 'numpy.int32'>, 7: <class 'numpy.int32'>, 'ulong': <class 'numpy.uint32'>, 'L': <class 'numpy.uint32'>, 8: <class 'numpy.uint32'>, 'longlong': <class 'numpy.int64'>, 'q': <class 'numpy.int64'>, 'ulonglong': <class 'numpy.uint64'>, 'Q': <class 'n

In [99]:
#реальное число типов данных    
print(*sorted(map(str, set(np.sctypeDict.values()))), sep = '\n')

<class 'numpy.bool_'>
<class 'numpy.bytes_'>
<class 'numpy.clongdouble'>
<class 'numpy.complex128'>
<class 'numpy.complex64'>
<class 'numpy.datetime64'>
<class 'numpy.float16'>
<class 'numpy.float32'>
<class 'numpy.float64'>
<class 'numpy.int16'>
<class 'numpy.int32'>
<class 'numpy.int64'>
<class 'numpy.int8'>
<class 'numpy.intc'>
<class 'numpy.longdouble'>
<class 'numpy.object_'>
<class 'numpy.str_'>
<class 'numpy.timedelta64'>
<class 'numpy.uint16'>
<class 'numpy.uint32'>
<class 'numpy.uint64'>
<class 'numpy.uint8'>
<class 'numpy.uintc'>
<class 'numpy.void'>


In [101]:
#в numpy есть свои типы bool_ и str_

a = True

print(type(a))

a = np.bool(a)
print(type(a))

a = np.bool_(a)
print(type(a))

<class 'bool'>
<class 'bool'>
<class 'numpy.bool_'>


C:\Users\Ulyana\AppData\Local\Temp\ipykernel_7708\989966363.py:7: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.bool(a)


In [110]:
#min число в 16 байт
min = int(- (2 ** 128)/2)

print(min)



-170141183460469231731687303715884105728


In [267]:
n = np.int16(-65536)
print(n)

0


In [266]:
#max число в 16 байт
(2**16)/2 -1

32767.0

In [105]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [111]:
a = np.uint8(-456)

print(a)

56


## Массивы 
→ Массив в программировании — это ещё одна структура данных. Она позволяет хранить элементы в заданном порядке точно так же, как это делают списки. 
Однако массивы обладают особым свойством: элемент по любому номеру из массива можно получить за одно и то же время. Другими словами, неважно, находится элемент в начале, в середине или в конце списка — на времени получения элемента из массива по индексу (номеру) это никак не скажется.

In [115]:
arr = np.array([1, 5, 2, 9, 10])

arr

#array([ 1,  5,  2,  9, 10])

array([ 1,  5,  2,  9, 10])

In [116]:
print(type(arr))
#<class 'numpy.ndarray'>

<class 'numpy.ndarray'>


In [117]:
# Перечислить список из списков можно
# было и в одну строку, но на нескольких
# строках получается нагляднее
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ])
nd_arr
# array([[12, 45, 78],
#        [34, 56, 13],
#        [12, 98, 76]])

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

In [118]:
arr.dtype

dtype('int32')

In [119]:
#можно сразу задать тип данных в массиве

arr = np.array([1, 5, 2, 9, 10], dtype = np.int8)

arr

array([ 1,  5,  2,  9, 10], dtype=int8)

In [120]:
#попробуем поместить в массив int8 число 2000

arr[2] = 2000

arr

array([  1,   5, -48,   9,  10], dtype=int8)

In [121]:
arr[2] = 125.5

arr

array([  1,   5, 125,   9,  10], dtype=int8)

In [122]:
#строку которую можно  преобразовать в число - можно добавить
arr[2] = '15'

arr

array([ 1,  5, 15,  9, 10], dtype=int8)

In [123]:
arr[2] = 'test'

arr

ValueError: invalid literal for int() with base 10: 'test'

In [125]:
#поменяем тип данных в массиве

arr = np.float64(arr)

arr


array([ 1.,  5., 15.,  9., 10.])

In [126]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

arr.ndim
# 1
nd_arr.ndim
# 2

arr.size
# 5
nd_arr.size
# 9

arr.shape
# (5,)
nd_arr.shape
# (3, 3)

arr.itemsize
# 1
nd_arr.itemsize
# 2

2

### Массив из нулей

In [ ]:
#создаем массив из нулей
zeros_1d = np.zeros(5)
zeros_1d
# array([0., 0., 0., 0., 0.])

In [127]:
zeros_3d = np.zeros((5,4,3), dtype=np.float32)
print(zeros_3d.shape)
# (5, 4, 3)

(5, 4, 3)


In [128]:
print(zeros_3d)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [129]:
#аналог range

np.arange(5)
# array([0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4])

In [130]:
# в отличае от range может принимать числа с точкой
np.arange(2.5, 5)
# array([2.5, 3.5, 4.5])

array([2.5, 3.5, 4.5])

In [131]:
# можно с шагом
np.arange(2.5, 5, 0.5)
# array([2.5, 3. , 3.5, 4. , 4.5])

array([2.5, 3. , 3.5, 4. , 4.5])

In [132]:
# можно сразу задать тип
np.arange(2.5, 5, 0.5, dtype=np.float16)
# array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

In [133]:
#лучше не использовать дробное число в качестве шага. вместо этого нужно использовать linspace

arr = np.linspace(1, 2, 10)
arr
# array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
#        1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [135]:
arr = np.linspace(1, 2, 10, endpoint = False)
arr
# array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
#        1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [137]:
arr, step = np.linspace(1, 2, 10, endpoint = False, retstep=True)
print(step)
# array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
#        1.55555556, 1.66666667, 1.77777778, 1.88888889, 2. 

0.1


In [139]:
print(np.finfo(np.float32))

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1.4012985e-45
---------------------------------------------------------------



In [140]:
arr = np.array([345234, 876362.12, 0, -1000, 99999999.], dtype = np.float32)
arr

array([ 3.452340e+05,  8.763621e+05,  0.000000e+00, -1.000000e+03,
        1.000000e+08], dtype=float32)

In [142]:
arr, step = np.linspace(-6, 21, 60, endpoint = True, retstep=True)
print(step)

0.4576271186440678


### Действия с массивами
#### Меняем форму массива

In [143]:
# создадим массив целых числе от 0 до 7 включительно

arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [144]:
# поменяем форму массива

arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [149]:
#создадим новый массив не  меняя форму предыдущего массива

arr = np.arange(8)
arr_new = arr.reshape(2, 4)

arr_new

#arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [148]:
# можно поменять форму разспределяя элементы не по строкам, а по столбцам
arr = np.arange(8)
arr_new = arr.reshape((2, 4), order = 'F') 

arr_new

#arr

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

#### Транспонирование массива

In [151]:
#транспонирование массива. т.е. замена строк на столбцы. С одномерными массивами такое не возможно (т.е. нельзя получить один столбец)
arr = np.arange(8)
arr.shape = (2, 4)

arr_trans = arr.transpose()

arr_trans

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

#### Индексация и срезы

In [152]:
arr = np.linspace(1, 2, 6)

arr

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [153]:
#выберем элемент по индексу
print(arr[2])

1.4


In [178]:
# выберем срез
print(arr[2:4])



[45 12]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [155]:
# срез в  обратном порядке. переворачиваем массив

print(arr[::-1])

[2.  1.8 1.6 1.4 1.2 1. ]


In [156]:
# с многомерными массивами

nd_arr = np.linspace(0, 6, 12, endpoint=False).reshape(3, 4 )
nd_arr

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [181]:
#индексация
nd_arr[1][2]
#3.0


3.0

In [158]:
#аналогично можно написать внутри одних квадратных скобок
nd_arr[1, 2]

3.0

In [159]:
#получим строки с нулевой по 2-ю невключительно, только 2-й столбец. При этом столбец стал строкой
nd_arr[:2, 2]

array([1., 3.])

In [160]:
# срез сразу по нескольким измерениям
nd_arr[1:, 2:4]

array([[3. , 3.5],
       [5. , 5.5]])

In [161]:
# все строки из массива и только два столбца

nd_arr[:, 2:4]

array([[1. , 1.5],
       [3. , 3.5],
       [5. , 5.5]])

In [162]:
# для последующих размерностей : указывать не обязательно. в примере ниже вернутся все столбцы

nd_arr[:2]

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5]])

#### Сортировка массивов

In [167]:
arr = np.array([23, 12, 45, 12, 23, 4, 15, 3])

arr_new = np.sort(arr)

print(arr)
print(arr_new)

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]


In [165]:
#если применим sort к массиву через точку, то он отсортируется

print(arr.sort())
#None

print(arr)
#[ 3  4 12 12 15 23 23 45]


None
[ 3  4 12 12 15 23 23 45]


#### Пропущенные данные nan

In [168]:
data = np.array([4, 9, -4, 3])

#попробуем извлеч квадратный корень. получим элемент nan - который показывает отсутствие числа в модуле numpy. В отличае от None, который явняется 
# типом None, nan имеет тип float

roots = np.sqrt(data)

roots

# C:\Users\Ulyana\AppData\Local\Temp\ipykernel_7708\309310424.py:5: RuntimeWarning: invalid value encountered in sqrt
#   roots = np.sqrt(data)
# array([2.        , 3.        ,        nan, 1.73205081])

C:\Users\Ulyana\AppData\Local\Temp\ipykernel_7708\309310424.py:5: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081])

In [170]:
# еще отличае None от nan - то что nan не равняются друг другу

print(None == None)
#True

print(np.nan == np.nan)
#False

True
False


In [172]:
#рекомендуемое сравнение через is
print(None is None)
#True
print(np.nan is np.nan)
#True
print(None is np.nan)
#False

True
True
False


In [173]:
#при попытке просуммировать все числа в массиве с пропущенным числом , получим nan
sum(roots)

nan

In [174]:
# проверям наличае nan

np.isnan(roots)
#array([False, False,  True, False])

array([False, False,  True, False])

In [175]:
# результат isnan можно использовать в качестве индекса

roots[np.isnan(roots)]

#array([nan])

array([nan])

In [176]:
# можем положить по данному индексу число 0

roots[np.isnan(roots)] = 0
roots

#array([2.        , 3.        , 0.        , 1.73205081])

array([2.        , 3.        , 0.        , 1.73205081])

In [177]:
#теперь можно просуммировать
sum(roots)

6.732050807568877

In [190]:
#задания
mystery = np.array(
[[-13586,  15203,   28445 ,-27117,  -1781, -17182 ,-18049],
 [ 25936, -30968,  -1297 , -4593 ,  6451,  15790,   7181],
 [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
 [ 13240,   7994 , 32592 , 20149,  13754,  11795 ,  -564],
 [-21725 , -8681 , 30305,  22260, -17918 , 12578,  29943],
 [-16841 ,-25392 ,-17278 , 11740,   5916,    -47 ,-32037]])


    
# В переменную elem_5_3 сохраните элемент из 5 строки и 3 столбца:
elem_5_3 = mystery[4, 2]

print(elem_5_3)

# В переменную last сохраните элемент из последней строки последнего столбца
last = mystery[-1, -1]

print(last)

# В переменную line_4 сохраните строку 4
line_4 = mystery[3]

print(line_4)

# В переменную col_2 сохраните предпоследний столбец
col_2 = mystery[:, -2]

print(col_2)

# Из строк 2-4 (включительно) получите столбцы 3-5 (включительно)
# Результат сохраните в переменную part
part = mystery[1:4, 2:5]

print(part)

#  Сохраните в переменную rev последний столбец в обратном порядке
rev = mystery[:, -1][::-1]

print('rev = ', rev)

# Сохраните в переменную trans транспонированный массив
trans = mystery.transpose()

print(trans)

30305
-32037
[13240  7994 32592 20149 13754 11795  -564]
[-17182  15790  25397  11795  12578    -47]
[[-1297 -4593  6451]
 [28655 -6012 21762]
 [32592 20149 13754]]
rev =  [-32037  29943   -564   8225   7181 -18049]
[[-13586  25936  13348  13240 -21725 -16841]
 [ 15203 -30968  28049   7994  -8681 -25392]
 [ 28445  -1297  28655  32592  30305 -17278]
 [-27117  -4593  -6012  20149  22260  11740]
 [ -1781   6451  21762  13754 -17918   5916]
 [-17182  15790  25397  11795  12578    -47]
 [-18049   7181   8225   -564  29943 -32037]]


In [208]:
mystery = np.array([ 12279. ,-26024.,  28745. ,    np.nan , 31244.,  -2365. , -6974. , -9212. ,    np.nan,
 -17722. , 16132.,  25933. ,    np.nan ,-16431. , 29810.])

 # Получите булевый массив с информацией о np.nan в массиве mystery
# True - значение пропущено, False - значение не пропущено


nans_index = np.isnan(mystery)
#print(nans_index)

# В переменную n_nan сохраните число пропущенных значений
n_nan = list(nans_index).count(True)
#print(n_nan)
# Заполните пропущенные значения в массиве mystery нулями
mystery[np.isnan(mystery)] = 0

#print(mystery)


# Поменяйте тип данных в массиве mystery на int32

mystery = np.int32(mystery)

#print(mystery)

# Отсортируйте значения в массиве по возрастанию и сохраните
# результат в переменную array
array = np.sort(mystery)

print(array)

# Сохраните в массив table двухмерный массив, полученный из массива array
# В нём должно быть 5 строк и 3 столбца. Причём порядок заполнения должен быть
# по столбцам! Например, 1, 2, 3, 4 -> 1    3
#                                      2    4
table = array.reshape((5, 3), order  = 'F')
print(table)

#  Сохраните в переменную col средний столбец из table
col = table[:, 1]

print(col)

[-26024 -17722 -16431  -9212  -6974  -2365      0      0      0  12279
  16132  25933  28745  29810  31244]
[[-26024  -2365  16132]
 [-17722      0  25933]
 [-16431      0  28745]
 [ -9212      0  29810]
 [ -6974  12279  31244]]
[-2365     0     0     0 12279]


## Операции с векторами
### Сложение векторов

Вектор - это одномерный массив

In [209]:
import numpy as np

vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])

#векторы можно складывать. при сложении векторов элементы складываются по-индексно

vec1 + vec2

array([14. , 10. , 10.6, 15.5])

In [210]:
#а если сложить два списка - то значения из одного списка добавятся в другой

list1 = [2, 4, 7, 2.5]
list2 = [12, 6, 3.6, 13]

list1 + list2

[2, 4, 7, 2.5, 12, 6, 3.6, 13]

In [211]:
#если нужно сложить значения двух списков, то нужно воспользоваться списочным сокращением

[x + y for x, y in zip(list1, list2)]

[14, 10, 10.6, 15.5]

In [212]:
#векторы можно перемножать. Для всех операций с векторами, эти векторы должны быть одинаковой длины

vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])

vec1*vec2

array([24. , 24. , 25.2, 32.5])

In [213]:
# Для операций с векторами, эти векторы должны быть одинаковой длины

vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6])

vec1*vec2

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
#вектор можно умножить на число, или производить любые операции с числами

vec1*2

In [214]:
#векторы можно сравнивать. Сравнение идет также поэлементно

vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])

vec1 > vec2

array([False, False,  True, False])

In [215]:
#веркторы можно сравнивать с числами
vec1 = np.array([2, 4, 7, 2.5])
vec1 > 3

array([False,  True,  True, False])

### Длина векторов

In [216]:
#посчитаем длину вектора
vec = np.array([3, 4])

length = np.sqrt(np.sum(vec**2))
print(length)

5.0


In [217]:
#также можно воспользоваться встроенными в Numpy элементами линейной алгебры. Так проще вычислить длину вектора
length = np.linalg.norm(vec)
print(length)

5.0


### Расстояние между векторами

In [219]:
#расстояние между векторами
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])

distance = np.sqrt(np.sum((vec1 - vec2)**2))
distance

12.206555615733702

In [ ]:
#расстояние между векторами с используем методов линейной алгебры. так как формула расстояния аналогична длине разницы векторов
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])

distance = np.linalg.norm(vec1 - vec2)
distance

### Скалярное произведение

In [220]:
#скалярное произведение
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)

scalar_product = np.sum(vec1*vec2)
scalar_product

250.0

In [221]:
scalar_product = np.dot(vec1, vec2)
scalar_product

250.0

In [222]:
#если скалярное произведение = 0, значит эти векторы перепндикулярны
x = np.array([25, 0])
y = np.array([0, 10])

np.dot(x, y)

0

### статистика


In [223]:
#базовая информация о статистических свойствах векторов

vec = np.array([2, 7, 18, 28, 1, 8, 4])

vec.min()

1

In [224]:
np.max(vec)

28

In [225]:
vec.mean()

9.714285714285714

## Случайные числа
### rand()

In [226]:
#Генерируем случайно число от 0 до 1
import numpy as np

np.random.rand()

0.8054012631467107

In [234]:
#генерируем случайные числа в диапазоне от 0 до 100

np.random.rand()*100

67.42211245731309

In [235]:
# получим одномерный массив из 5 чисел
np.random.rand(5)

array([0.6231724 , 0.12342088, 0.39716282, 0.52804751, 0.06777706])

In [236]:
# получим двумерный  массив 
np.random.rand(2, 3)

array([[0.10132568, 0.19622701, 0.89825226],
       [0.15406393, 0.72289014, 0.20962332]])

In [237]:
# получим многомерный  массив 
np.random.rand(2, 3, 4, 5)

array([[[[0.65342005, 0.17947039, 0.4485981 , 0.22295955, 0.63281023],
         [0.82019374, 0.59150975, 0.61341579, 0.71853548, 0.23572753],
         [0.25358272, 0.28881805, 0.68051996, 0.7573451 , 0.10304926],
         [0.23093659, 0.48886247, 0.89912522, 0.74470623, 0.25834966]],

        [[0.5111744 , 0.2917874 , 0.60507539, 0.81507216, 0.94293583],
         [0.04246878, 0.08949906, 0.8700407 , 0.14634581, 0.83626941],
         [0.83421474, 0.14995483, 0.93182644, 0.92462499, 0.40798532],
         [0.98293459, 0.00183775, 0.25558624, 0.66758454, 0.73341156]],

        [[0.96334023, 0.00953251, 0.77620021, 0.82849193, 0.92607057],
         [0.42159453, 0.67631744, 0.05523007, 0.40768519, 0.79893264],
         [0.21297629, 0.69545815, 0.60096149, 0.73057175, 0.32032707],
         [0.02736919, 0.85165503, 0.58630013, 0.17034969, 0.98026964]]],


       [[[0.94320611, 0.07651888, 0.7698463 , 0.79074258, 0.14390642],
         [0.94745742, 0.97913183, 0.79819812, 0.27531997, 0.25934017]

In [238]:
# обычно форма массива передается с помощью кортежа. но еслипросто передать кортеж в rand() то получим ошибку.
#  нужо распаковывать кортеж rand(*shape)

shape = (3, 4)

np.random.rand(*shape)

array([[0.62407727, 0.05315296, 0.25161302, 0.76262912],
       [0.10173218, 0.67603784, 0.01371764, 0.4251896 ],
       [0.2480109 , 0.10889026, 0.97367101, 0.89510126]])

### sample()

In [239]:
#аналог rand() - это функция sample(), которая принимает на вход форму в виде кортежа

shape = (3, 4)

np.random.sample(shape)

array([[0.85764881, 0.83747532, 0.24890494, 0.50540788],
       [0.65572788, 0.01361843, 0.12505329, 0.49496138],
       [0.79308744, 0.82861664, 0.52870998, 0.05549083]])

### uniform()

In [241]:
# запускаем без аргументов - получаем просто случайно число от 0 до 1
np.random.uniform()

0.4356926165438032

In [242]:
# можно передать аргументы - выставить граничные значения
np.random.uniform(-30, 50)

16.241111595952646

In [243]:
# с помощью size можно задать форму массива
np.random.uniform(-30, 50, size = 5)

array([  3.07036583, -10.19276344,  18.88676838, -16.20352162,
         5.32682224])

In [245]:
np.random.uniform(-30, 50, size = (2, 3))

array([[ 36.70254441,  35.75160053,  32.86268661],
       [ 41.59176511,  45.99663066, -21.51866568]])

### randint()
генерирует целочисленные данные

In [247]:
#если задать только один аргумент - то это будет верхняя граница диапазона. само значение не включается
np.random.randint(4, size = (2, 3))

array([[0, 2, 0],
       [3, 3, 2]])

In [249]:
#если передаем два аргумента, то первый аргумент становится нижней границей диапазона, а второй  - верхней
np.random.randint(6, 12,  size = (2, 3))

array([[10,  6,  9],
       [ 6,  8, 11]])

### shaffle()
применяется к массиву. перемешивает значения в массиве

In [250]:
arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [252]:
print(np.random.shuffle(arr))

arr

None


array([4, 0, 3, 2, 1, 5])

### permutation()

In [254]:
#если не хотим перемешивать сам массив, а только получить перемешанные значения

playlist = ['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']

shaffled = np.random.permutation(playlist)
print(shaffled)

['Pink Floyd' 'ACDC' 'The Beatles' 'Deep Purple']


In [255]:
# в permutation можно передать число и в результате полуим перемешанный массив из arange(). экономим действие

np.random.permutation(10)

array([8, 6, 5, 0, 3, 2, 1, 4, 9, 7])

### choice()
работа со случайными выборками. позволяет из массива данных выбрать какое-то подмножество случайным образом

In [256]:
# если передать одно число - то оно послужит для генерации arange

np.random.choice(5, size = (2, 3))

array([[0, 2, 0],
       [2, 3, 2]])

In [257]:
#создадим массив с работниками. replace = False - значит что выборка будет без повторений

workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']

choice = np.random.choice(workers, size = 2, replace = False)
print(choice)

['Nikita' 'Ivan']


In [258]:
#если потребовать выборку без повторений, размера больше, чем изначальных массив, то возникнет ошибка

workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']

choice = np.random.choice(workers, size = 10, replace = False)
print(choice)

ValueError: Cannot take a larger sample than population when 'replace=False'

In [259]:
# а потребовать больше элементов, с повторениями можно
choice = np.random.choice([1, 2, 3, 4, 5, 6], size = 10)
print(choice)

[3 5 4 2 5 6 5 6 5 5]


### seed()
компьютер обычно генерирует псевдослучайные числа, для генерации которых используется какое-то начальное число. Это число называется seed
Использование seed позволяет добится воспроизводимость заданной последовательности случайных чисел

seed должно быть >=0 и < 2**32 - 1  =  4294967295

In [263]:
np.random.seed(23)

print(np.random.randint(10, size = (3, 4)))

[[3 6 8 9]
 [6 8 7 9]
 [3 6 1 2]]


In [261]:
np.random.seed(100)

print(np.random.randint(10, size = 3))

print(np.random.randint(10, size = 3))

print(np.random.randint(10, size = 3))

[8 8 3]
[7 7 0]
[4 2 5]


In [262]:
2**32 - 1
#4294967295

4294967295

In [265]:
even = range(2, 17, 2)
print(list(even))

[2, 4, 6, 8, 10, 12, 14, 16]
